const Constants = {
    ACTIVE_TRUE: 1,
    ACTIVE_FALSE: 0,
    STATUS_CODE_SUCCESS: 1,
    STATUS_CODE_ERROR: 2,
    STATUS_CODE_UNAUTHORIZED_ACCESS: 3,
    STATUS_CODE_NOT_FOUND: 4,
    STATUS_CODE_DELETE_DENY: 5,
    STATUS_CODE_SUBMIT_DENY: 6,
    STATUS_CODE_AUTH_ROLE: 7,
    STATUS_CODE_INVALID_TOKEN: 8,
    COMP_STATUS_ACTIVE: 1,
    COMP_STATUS_INACTIVE: 2,
    COMP_STATUS_DEFECTIVE: 3,
    COMP_STATUS_ACTIVE_TEXT: "ACTIVE",
    COMP_STATUS_INACTIVE_TEXT: "INACTIVE",
    COMP_STATUS_DEFECTIVE_TEXT: "DEFECTIVE",
    ROLE_IT: 1,
    ROLE_COMMON_USER: 2,
    ROLE_SUPERADMIN: 3,
    N_A: "N/A",
    AXIOS_HEADER_POST_MULTIPART: {
                                    headers: {
                                        "Content-Type": "multipart/form-data"
                                    }
                                },
    arrOfMonths: [{id: 1, name:'Jan'},
                  {id: 2, name:'Feb'},
                  {id: 3, name:'Mar'},
                  {id: 4, name:'Apr'},
                  {id: 5, name:'May'},
                  {id: 6, name:'Jun'},
                  {id: 7, name:'Jul'},
                  {id: 8, name:'Aug'},
                  {id: 9, name:'Sept'},
                  {id: 10, name:'Oct'},
                  {id: 11, name:'Nov'},
                  {id: 12, name:'Dec'}],
    arrOfFullNameMonths: [{id: 1, name:'January'},
                          {id: 2, name:'February'},
                          {id: 3, name:'March'},
                          {id: 4, name:'April'},
                          {id: 5, name:'May'},
                          {id: 6, name:'June'},
                          {id: 7, name:'July'},
                          {id: 8, name:'August'},
                          {id: 9, name:'September'},
                          {id: 10, name:'October'},
                          {id: 11, name:'November'},
                          {id: 12, name:'December'}],
    arrOfFullNameMonthsFirstQtr: [{id: 1, name:'January'},
                                  {id: 4, name:'April'},
                                  {id: 7, name:'July'},
                                  {id: 10, name:'October'}],
    arrOfFullNameMonthsSecondQtr: [{id: 2, name:'February'},
                                   {id: 5, name:'May'},
                                   {id: 8, name:'August'},
                                   {id: 11, name:'November'}],
    arrOfFullNameMonthsThirdQtr: [{id: 3, name:'March'},
                                  {id: 6, name:'June'},
                                  {id: 9, name:'September'},
                                  {id: 12, name:'December'}],
    arrOfFullNameMonthsFirstOrderGroup: [{id: 1, name:'January'},
                                         {id: 2, name:'February'},
                                         {id: 3, name:'March'}],
    arrOfFullNameMonthsSecondOrderGroup: [{id: 4, name:'April'},
                                          {id: 5, name:'May'},
                                          {id: 6, name:'June'}],
    arrOfFullNameMonthsThirdOrderGroup: [{id: 7, name:'July'},
                                         {id: 8, name:'August'},
                                         {id: 9, name:'September'}],
    arrOfFullNameMonthsFourthOrderGroup: [{id: 10, name:'October'},
                                          {id: 11, name:'November'},
                                          {id: 12, name:'December'}],
    arrOfResolution: [{id: 1, name:'Complete'},
                      {id: 2, name:'Condemned'},
                      {id: 3, name:'Transferred'},
                      {id: 4, name:'Deferred'},
                      {id: 5, name:'Dropped'}],
    arrOfComputerStatus: [{id: 1, name:'Active'},
                          {id: 2, name:'Inactive'},
                          {id: 3, name:'Defective'}],
    arrOfComputerStatusWoDefective: [{id: 1, name:'Active'},
                                     {id: 2, name:'Inactive'}],
    arrOfStatus: [{id: true, name:'Active'},
                  {id: false, name:'Inactive'}],
    YEAR_SYSTEM_CREATED: 2022,
    BATCH_1: 1,
    BATCH_2: 2,
    BATCH_3: 3,
    COMP_INITIAL_BARCODE: "COMP",
    IP_TYPE_STATIC: 1,
    IP_TYPE_DYNAMIC: 2,
    IP_TYPE_STATIC_TEXT: "Static",
    IP_TYPE_DYNAMIC_TEXT: "Obtained",
    WSQ_STATUS_PENDING: 1,
    WSQ_STATUS_FOR_APPROVAL: 2,
    WSQ_STATUS_COMPLETE: 3,
    WSQ_STATUS_DISAPPROVE: 4,
    WSQ_RESOLUTION_COMPLETE: 1,
    WSQ_RESOLUTION_CONDEMNED: 2,
    WSQ_RESOLUTION_TRANSFERRED: 3,
    WSQ_RESOLUTION_DEFERRED: 4,
    WSQ_RESOLUTION_DROPPED: 5,
    WSQ_STATUS_PENDING_TEXT: "Pending",
    WSQ_STATUS_FOR_APPROVAL_TEXT: "For Approval",
    WSQ_STATUS_COMPLETE_TEXT: "Complete",
    WSQ_STATUS_DISAPPROVE_TEXT: "Disapprove",
    WSQ_RESOLUTION_COMPLETE_TEXT: "Complete",
    WSQ_RESOLUTION_CONDEMNED_TEXT: "Condemned",
    WSQ_RESOLUTION_TRANSFERRED_TEXT: "Transferred",
    WSQ_RESOLUTION_DEFERRED_TEXT: "Deferred",
    WSQ_RESOLUTION_DROPPED_TEXT: "Dropped",
    arrOfWorkstationStatus: [
        {id: 1, name: 'Pending'},
        {id: 2, name: 'For Approval'},
        {id: 3, name: 'Complete'},
        {id: 4, name: 'Disapprove'}
    ],
    arrOfMonthlyBatch: [
        {id: 1, name: '1st Month (Jan, Apr, July, Oct)'},
        {id: 2, name: '2nd Month (Feb, May, Aug, Nov)'},
        {id: 3, name: '3rd Month (Mar, Jun, Sept, Dec)'}
    ],
    EQUIPMENT_STATUS_OK: 1,
    EQUIPMENT_STATUS_DEFECTIVE: 2,
    EQUIPMENT_STATUS_NA: 3,
    EQUIPMENT_STATUS_OK_TEXT: "Ok",
    EQUIPMENT_STATUS_DEFECTIVE_TEXT: "Defective",
    EQUIPMENT_STATUS_NA_TEXT: "Not Applicable",
    DIALOG_SYSCOMP_SOFTWARE: 1,
    DIALOG_SYSCOMP_HARDWARE: 2,
    COMPONENT_TYPE_SOFTWARE: 1,
    COMPONENT_TYPE_HARDWARE: 2,
    SYSTEM_ID: 19,  //System Id of PMS from CAMS
    USER_SECRET_KEY: "Wm7KEm1hl67wCc@5XMDj6ZQeAKv$&tZ"
};

export default Constants;